ci: add automation script
folke/lua-dev.nvim pull request #56
Opened 2022-07-04 07:12 UTC by registerGen

This automates the process described in `BUILD.md`.

Please take a look at <https://github.com/registerGen/lua-dev.nvim/actions/runs/2608229895>. Is there anything that doesn't work correctly?

2022-09-01 10:07 UTC, folke requested changes
Looks good to me, except for the other comment

2022-09-01 10:07 UTC, folke commented on .github/workflows/ci.yml
> +    branches: [main]
This is awesome!

Just wondering if this won't trigger an indefinite loop?

Triggers on push to main, but the script itselfs pushes to main.

2022-09-01 10:11 UTC, merged

2022-09-01 10:15 UTC, folke commented
I removed the `on` push to `main` and added a manual trigger. I've also kept the weekly.

Thanks again for making this!

2022-09-02 13:05 UTC, registerGen commented
Thank you for reviewing this, too!